def throwError(x):
    print(x)
    quit()

def throwErrorCode(y):
    print(int(y))
    quit()

def throwErrorWithCode(x, y):
    print(f"{x}\nExiting with error code {y}")
    quit()
